
package com.dieauktion.inventoryservice.domain.globalenum;

public enum Category {
    // Agriculture & Farming
    LIVESTOCK,
    FARM_EQUIPMENT,
    TRACTORS,
    IRRIGATION_SYSTEMS,
    SEEDS_AND_PLANTS,
    FERTILIZERS,
    ANIMAL_FEED,
    FARMING_TOOLS,
    GREENHOUSE_EQUIPMENT,
    CROP_HARVESTING_EQUIPMENT,

    // Food & Beverage
    WINE,
    SPIRITS,
    BEER,
    GOURMET_FOODS,
    RESTAURANT_EQUIPMENT,
    COMMERCIAL_KITCHEN_GEAR,
    BAR_EQUIPMENT,
    FOOD_PROCESSING_EQUIPMENT,
    CATERING_SUPPLIES,
    VENDING_MACHINES,

    // Health & Beauty
    COSMETICS,
    SKINCARE_PRODUCTS,
    HAIR_CARE_PRODUCTS,
    HEALTH_SUPPLEMENTS,
    FITNESS_SUPPLEMENTS,
    SALON_EQUIPMENT,
    SPA_EQUIPMENT,
    MEDICAL_SUPPLIES,
    PHARMACY_EQUIPMENT,
    DENTAL_EQUIPMENT,

    // Crafts & Hobbies
    SEWING_SUPPLIES,
    KNITTING_SUPPLIES,
    SCRAPBOOKING_SUPPLIES,
    MODEL_TRAINS,
    RC_VEHICLES,
    DRONES,
    WOODWORKING_TOOLS,
    POTTERY_SUPPLIES,
    PAINTING_SUPPLIES,
    FABRIC_AND_TEXTILES,

    // Construction & Trade Tools
    CONSTRUCTION_EQUIPMENT,
    POWER_TOOLS,
    HAND_TOOLS,
    PLUMBING_SUPPLIES,
    ELECTRICAL_SUPPLIES,
    HVAC_EQUIPMENT,
    ROOFING_MATERIALS,
    BUILDING_MATERIALS,
    SAFETY_EQUIPMENT,
    SCAFFOLDING,

    // Textiles & Materials
    YARN,
    LEATHER_GOODS,
    RAW_MATERIALS,
    UPHOLSTERY_MATERIALS,
    CURTAINS_AND_BLINDS,
    CARPETS_AND_RUGS,
    VINTAGE_TEXTILES,
    QUILTS,
    TAPESTRIES,
    FABRIC_REMNANTS,

    // Professional Services Equipment
    PRINTING_EQUIPMENT,
    PHOTOGRAPHY_EQUIPMENT,
    RESTAURANT_FURNITURE,
    RETAIL_FIXTURES,
    MANNEQUINS,
    CASH_REGISTERS,
    POS_SYSTEMS,
    COMMERCIAL_CLEANING_EQUIPMENT,
    JANITORIAL_SUPPLIES,
    PACKAGING_EQUIPMENT,

    // Recreation & Entertainment
    ARCADE_GAMES,
    PINBALL_MACHINES,
    POOL_TABLES,
    DART_BOARDS,
    CASINO_EQUIPMENT,
    THEATER_EQUIPMENT,
    STAGE_LIGHTING,
    SOUND_EQUIPMENT,
    DJ_EQUIPMENT,
    PARTY_SUPPLIES,

    // Marine & Aviation
    BOAT_PARTS,
    MARINE_ELECTRONICS,
    FISHING_EQUIPMENT,
    DIVING_EQUIPMENT,
    AVIATION_PARTS,
    PILOT_EQUIPMENT,
    NAUTICAL_INSTRUMENTS,
    BOAT_MOTORS,
    AIRCRAFT_INSTRUMENTS,
    MARINE_SAFETY_EQUIPMENT,

    // Specialized Collections
    MILITARIA,
    FOSSILS,
    MINERALS,
    METEORITES,
    SCIENTIFIC_INSTRUMENTS,
    VINTAGE_ADVERTISING,
    HISTORICAL_DOCUMENTS,
    MAPS,
    GLOBES,
    TIMEPIECES
}
